import { EXAMS } from "@/configs/exams";
import type { Metadata } from "next";
import type { ReactNode } from "react";

type Props = {
  children: ReactNode;
  params: Promise<{ examName: string }>;
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ examName: string }>;
}): Promise<Metadata> {
  const { examName } = await params;
  const exam = EXAMS.find((e) => e.routeParam === examName);

  if (!exam) {
    return {
      title: "Exam Not Found | Quiz Mint AI",
    };
  }

  return {
    title: `${exam.pageLabel} Practice Quiz | Quiz Mint AI`,
    description: `Free AI-powered practice questions and quizzes for ${exam.name}. Prepare for your ${exam.menuLabel} exam with our intelligent quiz generator. Unlimited practice questions with detailed explanations.`,
    keywords: [
      exam.name,
      exam.menuLabel,
      "practice exam",
      "quiz generator",
      "certification",
      "AI questions",
      "mock test",
    ],
    openGraph: {
      title: `${exam.pageLabel} Practice Quiz | Quiz Mint AI`,
      description: `Free AI-powered practice questions for ${exam.name}. Prepare effectively with our intelligent quiz generator.`,
      type: "website",
    },
  };
}

export default async function ExamLayout({ children, params }: Props) {
  const { examName } = await params;
  const exam = EXAMS.find((e) => e.routeParam === examName);

  return (
    <div>
      <h1 className="md:text-2xl font-bold mb-4">{exam?.pageLabel}</h1>
      <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 mb-6">
        <div className="flex">
          <div className="flex-shrink-0">
            <svg
              className="h-5 w-5 text-yellow-400"
              viewBox="0 0 20 20"
              fill="currentColor"
              aria-hidden="true"
            >
              <title>Warning Icon</title>
              <path
                fillRule="evenodd"
                d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z"
                clipRule="evenodd"
              />
            </svg>
          </div>
          <div className="ml-3">
            <p className="text-sm text-yellow-700">
              Warning: All questions in this system are generated by AI and are
              not actual exam questions or past papers. Users are advised to
              exercise their own judgment regarding the applicability and
              accuracy of the questions.
            </p>
          </div>
        </div>
      </div>
      {children}
    </div>
  );
}
